# None of our tests should take longer than 45s, and if they've gone 2x that,
# terminate them to prevent infinite run-on.
[profile.default]
slow-timeout = { period = "45s", terminate-after = 2 }
fail-fast = false
retries = 0

# Use two threads for tests with "2 threads" in their name
[[profile.default.overrides]]
filter = 'test(~2_threads) | test(~2 threads)'
threads-required = 2

# Use four threads for tests with "4 threads" in their name
[[profile.default.overrides]]
filter = 'test(~4_threads) | test(~4 threads)'
threads-required = 4

# Use eight threads for tests with "8 threads" in their name
[[profile.default.overrides]]
filter = 'test(~8_threads) | test(~8 threads)'
threads-required = 8

#
# Workarounds for flaky tests
#

# https://github.com/gfx-rs/wgpu/issues/7200
[[profile.default.overrides]]
filter = 'test(wgpu_test::image_atomics::image_32_atomics)'
# platform = 'cfg(target_vendor = "apple")'
retries = 1
